spring:
  application:
    name: jpa

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/C:/workspace/KH/reactbackend/tdb
#      jdbc-url: jdbc:h2:tcp://localhost/C:/test/11_SpringBoot/reactbackend/tdb
      driver-class-name: org.h2.Driver
      username: sa
      password:

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: "http://localhost:8888/login/oauth2/code/google"
            scope: openid, email, profile
            authorization-grant-type: authorization_code
          kakao:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8888/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
          naver: # 제공자 이름 (임의로 지정 가능)
            provider: naver
            client-name: Naver
            client-id:
            client-secret:
            scope: name, email
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8888/login/oauth2/code/naver" # 개발자센터에 해당 URL 등록 https://example.com/login/oauth2/code/naver

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mail:
    host: smtp.gmail.com
    port: 587
    username: wotejal1234@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: 8888

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: JaOmRTrD8ApXk2p/E5i04AxX6HdV3QCF0HntfC8Xmf3YW76APVb9xgTOffrCOC44Khjjb2/WZB3IxTRshBATbw==
  expiration: 3000

oauth:
  kakao:
    client_id: 51271a4185d2c31ec1ad07297bfb58b1
    redirect_uri: http://localhost:5173/oauth/kakao/redirect